# library(reticulate)
# use_python("/home/dnguyen/anaconda3/bin/python")
# 
# source_python("python/kmedoids.py")
# source_python("python/distance.py")
# source_python("python/distance1.py")
# source_python("python/distance2.py")
# source_python("python/distance3.py")
# source_python("python/neighborhood.py")
# source_python("python/util.py")
# source_python("python/alignment.py")
# source_python("python/correspondence.py")
# source_python("python/dtw.py")
# source_python("python/embedding.py")
# # source_python("python/viz.py")
# source_python("python/warping.py")
